### PR TITLE
Updated dependencies and added tests

### PR DESCRIPTION
**Pull request by vtrifonov**
- Updated bcel and common-io dependencies
- Added test functionality for validating the tool output
Related to #25

### CODE REVIEW

**Review by NathanaelA — CHANGES_REQUESTED** [review]
Hey, can you either reset the PR to use all these these JAR's/LIB'S that already exist in `libs/`
https://github.com/NativeScript/android-dts-generator/tree/master/libs/androidx/1.0.0
OR move them from libs/ to this location (and make sure whatever points to libs is updated).   But we probably don't want TWO copies of most these in git...

**Comment by vtrifonov** [comment]
sure, I can do this, but then if they are changed, the expected result should also be replaced

**Comment by vtrifonov** [comment]
Done! Added also a note in the readme

**Review by NathanaelA — APPROVED** [review]

**Comment by NathanaelA** [comment]
Thank you @vtrifonov - Awesome work.

**Pull request merged**
